export { default as AcademicYear } from './AcademicYear';
export { default as About } from './About';
export { default as CourseEval } from './CourseEval';
export { default as Courses } from './Courses';
export { default as Grades } from './Grades';
export { default as ImportGrades } from './ImportGrades';
export { default as GradeMetrics } from './GradeMetrics';
export { default as GuestEval } from './GuestEval';
export { default as GuestLecturers } from './GuestLecturers';
export { default as Home } from './Home';
export { default as GuestEvalMetrics } from './GuestEvalMetrics';
export { default as CourseEvalMetrics } from './CourseEvalMetrics';
export { default as ImportGuestEval} from './ImportGuestEval';
export { default as ImportGuestEvalMan} from './ImportGuestEvalMan';
export { default as ImportCourseEval } from './ImportCourseEval';
export { default as ImportCourseEvalMan } from './ImportCourseEvalMan';
export { default as GuestEvalEdit } from './GuestEvalEdit';
export { default as CourseEvalEdit } from './CourseEvalEdit';